/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.shopcoffee;

import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.File;
import java.util.Date;

import java.io.IOException;

/**
 *
 * @author COMPUTER
 */
public class Coffee extends javax.swing.JFrame {

    /**
     * Creates new form Coffee
     */
    public Coffee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CB1 = new javax.swing.JCheckBox();
        CB2 = new javax.swing.JCheckBox();
        CB3 = new javax.swing.JCheckBox();
        CB4 = new javax.swing.JCheckBox();
        CB5 = new javax.swing.JCheckBox();
        CB7 = new javax.swing.JCheckBox();
        CB8 = new javax.swing.JCheckBox();
        CB9 = new javax.swing.JCheckBox();
        CB10 = new javax.swing.JCheckBox();
        CB11 = new javax.swing.JCheckBox();
        CB12 = new javax.swing.JCheckBox();
        CB13 = new javax.swing.JCheckBox();
        CB14 = new javax.swing.JCheckBox();
        CB15 = new javax.swing.JCheckBox();
        CB16 = new javax.swing.JCheckBox();
        CB17 = new javax.swing.JCheckBox();
        CB18 = new javax.swing.JCheckBox();
        CB19 = new javax.swing.JCheckBox();
        CB20 = new javax.swing.JCheckBox();
        CB21 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        CB39 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CB40 = new javax.swing.JCheckBox();
        CB22 = new javax.swing.JCheckBox();
        CB23 = new javax.swing.JCheckBox();
        CB24 = new javax.swing.JCheckBox();
        CB26 = new javax.swing.JCheckBox();
        CB27 = new javax.swing.JCheckBox();
        CB29 = new javax.swing.JCheckBox();
        CB30 = new javax.swing.JCheckBox();
        CB31 = new javax.swing.JCheckBox();
        CB32 = new javax.swing.JCheckBox();
        CB33 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        CB34 = new javax.swing.JCheckBox();
        CB35 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        CB36 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        CB37 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        CB38 = new javax.swing.JCheckBox();
        CB41 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CB42 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JP1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        JTF1 = new javax.swing.JTextField();
        JTF2 = new javax.swing.JTextField();
        JTF3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Esspresso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 77, 80, 39));

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Americano");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 126, 80, 39));

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Latte");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 174, 80, 39));

        jLabel7.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cappuccino");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 223, 80, 39));

        jLabel8.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Green Tea");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 271, 80, 39));

        jLabel9.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Thai Tea");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 320, 80, 39));

        jLabel10.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CoCoa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 367, 80, 39));

        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 86, -1, -1));
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 86, -1, -1));
        getContentPane().add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 86, -1, -1));
        getContentPane().add(CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 135, -1, -1));
        getContentPane().add(CB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 135, -1, -1));
        getContentPane().add(CB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 184, -1, -1));
        getContentPane().add(CB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 184, -1, -1));
        getContentPane().add(CB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 184, -1, -1));
        getContentPane().add(CB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 232, -1, -1));
        getContentPane().add(CB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 232, -1, -1));
        getContentPane().add(CB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 232, -1, -1));
        getContentPane().add(CB13, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 279, -1, -1));
        getContentPane().add(CB14, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 279, -1, -1));
        getContentPane().add(CB15, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 279, -1, -1));
        getContentPane().add(CB16, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 328, -1, -1));
        getContentPane().add(CB17, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 328, -1, -1));
        getContentPane().add(CB18, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 328, -1, -1));
        getContentPane().add(CB19, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 375, -1, -1));
        getContentPane().add(CB20, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 375, -1, -1));
        getContentPane().add(CB21, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 375, -1, -1));

        jLabel12.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nestcafe");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 271, 80, 39));
        getContentPane().add(CB39, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 328, -1, -1));

        jLabel13.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nestcafe Tea");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 320, 80, 39));

        jLabel14.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Italian Soda (Cantaloupe,\nStrawberry, Apple, BlueHawai)"); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 416, 310, 39));
        getContentPane().add(CB40, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 473, -1, -1));
        getContentPane().add(CB22, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 86, -1, -1));
        getContentPane().add(CB23, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 86, -1, -1));
        getContentPane().add(CB24, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 86, -1, -1));
        getContentPane().add(CB26, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 135, -1, -1));
        getContentPane().add(CB27, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 135, -1, -1));
        getContentPane().add(CB29, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 184, -1, -1));
        getContentPane().add(CB30, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 184, -1, -1));
        getContentPane().add(CB31, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 232, -1, -1));
        getContentPane().add(CB32, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 232, -1, -1));
        getContentPane().add(CB33, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 232, -1, -1));

        jLabel15.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Milk");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 77, 80, 39));
        getContentPane().add(CB34, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 279, -1, -1));
        getContentPane().add(CB35, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 279, -1, -1));

        jLabel16.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Milk Tea");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 126, 80, 39));
        getContentPane().add(CB36, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 279, -1, -1));

        jLabel17.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Lemon Tea");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 174, 80, 39));
        getContentPane().add(CB37, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 328, -1, -1));

        jLabel18.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Milo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 223, 80, 39));
        getContentPane().add(CB38, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 328, -1, -1));
        getContentPane().add(CB41, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 509, -1, -1));

        jLabel19.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Red lime Soda");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 500, 80, 39));

        jLabel20.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Honey lime Soda");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 557, 80, 39));
        getContentPane().add(CB42, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 564, -1, -1));

        jLabel11.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hot");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 46, 42, 31));

        jLabel21.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Ice");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 42, 31));

        jLabel22.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Frappe");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 46, 62, 31));

        jLabel23.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Hot");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 46, 42, 31));

        jLabel24.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ice");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 46, 42, 31));

        jLabel25.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Frappe");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 46, 62, 31));

        jButton1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jButton1.setText("BUY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 604, 101, 32));

        jButton2.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 604, 101, 32));

        jScrollPane1.setViewportView(JP1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 386, 321, 200));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel1.setText("Price");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 427, 49, 35));

        JTF1.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        JTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(JTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 426, 113, -1));

        JTF2.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        JTF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(JTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 472, 113, -1));

        JTF3.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        JTF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(JTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 518, 113, -1));

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel2.setText("Change");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 519, -1, 35));

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel3.setText("Received");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 473, -1, 35));

        jButton3.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jButton3.setText("Receipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 604, 101, 32));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Bookman Old Style", 1, 39)); // NOI18N
        jLabel26.setText("FTM Coffee Cafe");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 340, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon("D:\\รูป\\8811AB3A7BC7414A9325F4DDA32FA7FE.jpg")); // NOI18N
        jLabel27.setText("jLabel27");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1140, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = "";
        Date date = new Date();
        int money = 0;
if(CB1.isSelected() == true){
money = money+35;
name += "Esspresso(Hot)          35$\n";
}
if(CB2.isSelected() == true){
money = money+45;
name += "Esspresso(Ice)          45$\n";
}
if(CB3.isSelected() == true){
money = money+50;
name += "Esspresso(Frappe)          50$\n";
}
if(CB4.isSelected() == true){
money = money+35;
name += "Americano(Hot)          35$\n";
}
if(CB5.isSelected() == true){
money = money+45;
name += "Americano(Ice)          45$\n";
}
if(CB7.isSelected() == true){
money = money+35;
name += "Latte(Hot)          35$\n";
}
if(CB8.isSelected() == true){
money = money+45;
name += "Latte(Ice)          45$\n";
}
if(CB9.isSelected() == true){
money = money+50;
name += "Latte(Frappe)          50$\n";
}
if(CB10.isSelected() == true){
money = money+35;
name += "Cappuccino(Hot)          35B\n";
}
if(CB11.isSelected() == true){
money = money+45;
name += "Cappuccino(Ice)          45$\n";
}
if(CB12.isSelected() == true){
money = money+50;
name += "Cappuccino(Frappe)          50$\n";
}
if(CB13.isSelected() == true){
money = money+20;
name += "Green Tea(Hot)          20$\n";
}
if(CB14.isSelected() == true){
money = money+25;
name += "Green Tea(Ice)          25$\n";
}
if(CB15.isSelected() == true){
money = money+30;
name += "Green Tea(Frappe)          30$\n";
}
if(CB16.isSelected() == true){
money = money+20;
name += "Thai Tea(Hot)          20$\n";
}
if(CB17.isSelected() == true){
money = money+25;
name += "Thai Tea(Ice)          25$\n";
}
if(CB18.isSelected() == true){
money = money+30;
name += "Thai Tea(Frappe)          30$\n";
}
if(CB19.isSelected() == true){
money = money+20;
name += "CoCoa(Hot)          20B\n";
}
if(CB20.isSelected() == true){
money = money+25;
name += "CoCoa(Ice)          25$\n";
}
if(CB21.isSelected() == true){
money = money+25;
name += "CoCoa(Frappe)          30$\n";
}
if(CB22.isSelected() == true){
money = money+30;
name += "Milk(Hot)          20$\n";
}
if(CB23.isSelected() == true){
money = money+25;
name += "Milk Tea(Ice)          25$\n";
}
if(CB24.isSelected() == true){
money = money+30;
name += "Milk Tea(Frappe)          30$\n";
}
if(CB26.isSelected() == true){
money = money+25;
name += "Lemon Tea(Ice)          25$\n";
}
if(CB27.isSelected() == true){
money = money+30;
name += "Lemon Tea(Frappe)          30$\n";
}
if(CB29.isSelected() == true){
money = money+25;
name += "Milo(Ice)          25$\n";
}
if(CB30.isSelected() == true){
money = money+30;
name += "Milo(Frappe)          30$\n";
}
if(CB31.isSelected() == true){
money = money+20;
name += "Milo(Hot)          20$\n";
}
if(CB32.isSelected() == true){
money = money+25;
name += "Milo(Ice)          25$\n";
}
if(CB33.isSelected() == true){
money = money+30;
name += "Milo(Frappe)          30$\n";
}
if(CB34.isSelected() == true){
money = money+20;
name += "Nestcafe(Hot)          20$\n";
}
if(CB35.isSelected() == true){
money = money+25;
name += "Nestcafe(Ice)          25$\n";
}
if(CB36.isSelected() == true){
money = money+30;
name += "Nestcafe(Frappe)          30$\n";
}
if(CB37.isSelected() == true){
money = money+25;
name += "Nestcafe Tea(Hot)          20$\n";
}
if(CB38.isSelected() == true){
money = money+25;
name += "Nestcafe Tea(Ice)          25$\n";
}
if(CB39.isSelected() == true){
money = money+25;
name += "Nestcafe Tea(Frappe)          30$\n";
}
if(CB40.isSelected() == true){
money = money+35;
name += "Italian Soda (Cantaloupe, Strawberry, Apple, BlueHawai)(Frappe)          25$\n";
}
if(CB41.isSelected() == true){
money = money+25;
name += "Red lime Soda(Ice)          25$\n";
}
if(CB42.isSelected() == true){
    money = money+25;
name += "Honey lime Soda(Ice)          25$\n";
}
JTF1.setText(String.valueOf(money));
JP1.setText(name);
Double e,f,c ;
e=Double.parseDouble(JTF2.getText());
c=e-money; 
JTF3.setText(""+c);

//Feed FD = new Feed();
//FD.show();
    


    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JTF1.setText("");
JTF2.setText("");
JTF3.setText("");
JP1.setText("");
CB1.setSelected(false);
CB2.setSelected(false);
CB3.setSelected(false);
CB4.setSelected(false);
CB5.setSelected(false);
CB7.setSelected(false);
CB8.setSelected(false);
CB9.setSelected(false);
CB10.setSelected(false);
CB11.setSelected(false);
CB12.setSelected(false);
CB13.setSelected(false);
CB14.setSelected(false);
CB15.setSelected(false);
CB16.setSelected(false);
CB17.setSelected(false);
CB18.setSelected(false);
CB19.setSelected(false);
CB20.setSelected(false);
CB21.setSelected(false);
CB22.setSelected(false);
CB23.setSelected(false);
CB24.setSelected(false);
CB26.setSelected(false);
CB27.setSelected(false);
CB29.setSelected(false);
CB30.setSelected(false);
CB31.setSelected(false);
CB32.setSelected(false);
CB33.setSelected(false);
CB34.setSelected(false);
CB35.setSelected(false);
CB36.setSelected(false);
CB37.setSelected(false);
CB38.setSelected(false);
CB39.setSelected(false);
CB40.setSelected(false);
CB41.setSelected(false);
CB42.setSelected(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\comzone\\Downloads\\Receipt.txt";
        File file = new File(path);
        FileWriter writer;
        try{
            writer = new FileWriter(file,true);
            writer.write(JP1.getText());
            writer.close();
            
            System.out.println("Write success !");
        }catch(IOException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,JP1);
    }//GEN-LAST:event_jButton3ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CB1;
    private javax.swing.JCheckBox CB10;
    private javax.swing.JCheckBox CB11;
    private javax.swing.JCheckBox CB12;
    private javax.swing.JCheckBox CB13;
    private javax.swing.JCheckBox CB14;
    private javax.swing.JCheckBox CB15;
    private javax.swing.JCheckBox CB16;
    private javax.swing.JCheckBox CB17;
    private javax.swing.JCheckBox CB18;
    private javax.swing.JCheckBox CB19;
    private javax.swing.JCheckBox CB2;
    private javax.swing.JCheckBox CB20;
    private javax.swing.JCheckBox CB21;
    private javax.swing.JCheckBox CB22;
    private javax.swing.JCheckBox CB23;
    private javax.swing.JCheckBox CB24;
    private javax.swing.JCheckBox CB26;
    private javax.swing.JCheckBox CB27;
    private javax.swing.JCheckBox CB29;
    private javax.swing.JCheckBox CB3;
    private javax.swing.JCheckBox CB30;
    private javax.swing.JCheckBox CB31;
    private javax.swing.JCheckBox CB32;
    private javax.swing.JCheckBox CB33;
    private javax.swing.JCheckBox CB34;
    private javax.swing.JCheckBox CB35;
    private javax.swing.JCheckBox CB36;
    private javax.swing.JCheckBox CB37;
    private javax.swing.JCheckBox CB38;
    private javax.swing.JCheckBox CB39;
    private javax.swing.JCheckBox CB4;
    private javax.swing.JCheckBox CB40;
    private javax.swing.JCheckBox CB41;
    private javax.swing.JCheckBox CB42;
    private javax.swing.JCheckBox CB5;
    private javax.swing.JCheckBox CB7;
    private javax.swing.JCheckBox CB8;
    private javax.swing.JCheckBox CB9;
    private javax.swing.JTextPane JP1;
    private javax.swing.JTextField JTF1;
    private javax.swing.JTextField JTF2;
    private javax.swing.JTextField JTF3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void ClearData() {
    }


    }
        
   
